[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.virtualenv", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "cd backend && python -m venv venv",
  "cd backend && source venv/bin/activate && pip install --no-cache-dir -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build] 
cmds = [
  "cd frontend && yarn build"
]

[start]
cmd = "cd backend && source venv/bin/activate && python server.py"